### ISSUE TITLE
Convert classical ML examples into quantum tutorials

### ISSUE THREAD

**Issue by adekusar-drl** [qiskit-advocate/qamp-fall-21#26]
# Description

Quantum machine learning is gaining momentum and becoming more and more popular across machine learning researchers. This project aims facilitating smooth transition from classical to quantum machine learning algorithms for those who are already proficient in classical ML. The goal of this project is to pick up a small classical machine learning dataset and an ML problem, e.g. classification, regression, then build up a quantum model that will produce similar results. The dataset should be small enough to be processed by a quantum computer or a simulator, but in the same time it should be widely known by ML practitioners. A trained quantum model can be a contribution to Qiskit Machine Learning model zoo.

# Mentor/s
Anton Dekusar, @adekusar-drl
Research Software Engineer / Qiskit Machine Learning contributor
Availability depends on other projects: #13 and #14.

# Type of participant
- Proficiency in classic machine learning algorithms
- Basic knowledge of quantum machine learning
- Excellent writing skills and proficiency in jupyter notebook

# Number of participants
1+

# Deliverable
A jupyter notebook explaining how to move from a classical algorithm an analogous quantum one. A trained model can be a contribution to Qiskit Machine Learning.

**Comment by SiddharthaMorales** [comment]
I'd like to contibute in this issue if possible

**Comment by adarsh1chand** [comment]
Interested to contribute.

**Comment by gunchamalik** [comment]
I do not have knowledge on Quantum Machine Learning. I had done basic machine learning course about 3 years back. I will be interested in learning Quantum Machine Learning and contributing to the tutorials.

**Comment by EACMichiels** [comment]
This looks great. I would like to join! I applied as one of my options!

**Comment by HuangJunye** [comment]
Close due to limited availability of the mentor (who is mentoring project #13 and #14 )
