### ISSUE TITLE
Quantum Internet Simulator 

### ISSUE THREAD

**Issue by bala-ceg** [qiskit-advocate/qamp-fall-21#31]
# Description
I am a beginner in the field of QC. I am a Quantum and Network enthusiast. 
Out of my  enthusiasm, I proposing the project End to End Quantum Internet software Simulator discussed in the below documents
The document references: 
https://datatracker.ietf.org/doc/draft-irtf-qirg-quantum-internet-use-cases/

Paper from Mitesh https://arxiv.org/pdf/2003.06397.pdf

# Mentor/s
Looking for the ideal mentor 

# Type of participant
Someone interested in the quantum internet

# Number of participants
1-3
# Deliverable
Working  prototype and paper (maybe a qiskit chapter)

**Comment by AlainChance** [comment]
Worth checking: Aliro offers [Aliro™ Q.Network](https://www.aliroquantum.com/product/network?hsLang=en), the first commercial Entanglement as a Service platform, with "Run simulation" and "Get simulation analysis" features.

**Comment by bala-ceg** [comment]
Thank you sir @AlainChance  for the suggestions.

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
