### ISSUE TITLE
Quantum Trim

### ISSUE THREAD

**Issue by asgunzi** [qiskit-advocate/qamp-fall-21#36]
# Description
The cutting stock problem is used in every paper company in the world. It can be modeled using integer programming, and one of the subproblems is the famous knapsack problem.

The project is to model the Trim problem using different quantum computing algorithms (Grover? QAOA?) and to compare the techniques. 
https://en.wikipedia.org/wiki/Cutting_stock_problem
It is a real world problem, well defined problem, and can be a case study on quantum optimization.

# Mentor/s
Are you able to mentor this project? I can help to give the integer programming formulation and some other practical aspects, but I need the help of mentors to do the quantum formulation of it.

# Type of participant
- Interest on optimization, qaoa, grover and similar

# Number of participants
3

# Deliverable
An quantum algorithm to solve the Trim problem, comparisons between it and integer programming formulation.

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
