### ISSUE TITLE
Can entanglement be used as a resource in quantum machine learning ?

### ISSUE THREAD

**Issue by adarsh1chand** [qiskit-advocate/qamp-fall-21#37]
# Description
### *Background*
Bell non-local games such as CHSH game (see https://www.youtube.com/watch?v=sUQYSy6C1aA) use entangled quantum systems as resource to produce non-local correlations which are signatures of truly quantum behavior. This is evidenced by the fact that these correlations violate certain inequalities which are obeyed by any local realistic (classical) system (see for example, Bell's inequality in [this](https://learn.qiskit.org/course/ch-demos/local-reality-and-the-chsh-inequality) chapter of qiskit textbook). Recently, these inequalities have been used to produce entangled states using reinforcement learning, in which the reward for the agent is the extent of violation of the inequality (how far away is the measured outcome from the upper bound given by the inequality), see this paper by [Bharti et al](https://arxiv.org/pdf/1912.10783.pdf).

### *Goal*
To study the effect of using entangled quantum systems as a resource on the learning of hybrid classical-quantum models.

For example, Suppose we have a dataset D which is provided as input to two classical neural networks (NN(1) and NN(2)) which output rotation angles for two parameterized quantum circuits, each of which act on individual qubits of a Bell pair (i.e, the circuits act locally on each qubit) and we measure a set of observables as <O1, O2> (O1 and O2 are local measurements on each qubit). Now depending on measurement outcomes of <O1, O2> we can construct CHSH (or Bell) type inequality which can then be used as cost function for training the neural networks, in the hope that non-local correlations between the qubits have an effect on the learning of individual neural networks. We can ask questions like:
- What can we say about the representation (parameter values of the neural network) learnt by each classical NN (NN(1) and NN(2))  ? how are they related to each other ? 
- If the representations are related, can entangled quantum systems be useful in practical machine learning for instance, is this framework useful in multi-task learning in a hybrid classical-quantum setting ?
- Are there inequalities which have practical use for learning useful patterns in some dataset D ?
- What about extending this to multi-partite entangled systems with NN(1), NN(2), NN(3)...NN(k) each learning rotations angles for k qubits with some entanglement layout between them ?

And many more...

# Mentor/s
Looking for mentors and collaborators.

# Type of participant
Interested in quantum machine learning.

# Number of participants
1+

# Deliverable
A jupyter notebook which is a case study of the goal mentioned above. Focus on extracting meaningful insights from the representations learnt by the neural networks, correlation between them etc.

**Comment by AlainChance** [comment]
It is worth considering the insights from the [2021-08-26 QML Meetup: Hsin-Yuan (Robert) Huang, Power of data in quantum machine learning](https://www.youtube.com/watch?v=eSvib4kXkIk), particulary the following one in the Conclusion shown at 44:36:
> Data challenge quantum advantage in ML problems.

Huang, HY., Broughton, M., Mohseni, M. et al. Power of data in quantum machine learning. Nat Commun 12, 2631 (2021). [https://doi.org/10.1038/s41467-021-22539-9](https://doi.org/10.1038/s41467-021-22539-9)

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
