### ISSUE TITLE
Quantum-secure communication of data over internet

### ISSUE THREAD

**Issue by HitanshuGedam** [qiskit-advocate/qamp-fall-21#38]
# Description

I don't have a very specific idea in mind but this is focused around quantum cryptography and communication. This project will be based around creating some cryptography techniques to ensure quantum-secure data being stored or transported over networks. Building strong cryptographic algorithms for security of big data which contains important information like financial transactions, healthcare information, personal information etc. is the idea behind this project. It covers security of networks, communication channels and data which travels through it.  

# Mentor/s
Looking for mentor(s).

# Type of participant
People who are enthusiastic about security and know the fundamentals of hacking, like how the web works, how data is transmitted, people who have knowledge about cryptography and enjoy mathematics behind CS.

# Number of participants
3-5

# Deliverable
A solution for problems of huge data breaches to ensure the security and integrity of data while it is at rest or in transit. A quantum solution in the form of a cryptography algorithm or a technique.

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
