### ISSUE TITLE
Picturing Quantum Processes: A First Course in Quantum Theory and Diagrammatic Reasoning + ZX calculus

### ISSUE THREAD

**Issue by amitracal** [qiskit-advocate/qamp-fall-21#40]
# Description
Bob Coecke and Aleks Kissinger in their iconic book named "Picturing Quantum Processes: A First Course in Quantum Theory and Diagrammatic Reasoning" presents a beautiful and more intutive alternative representation to quantum operations. This can be a game changer in quantum education and research and because this pictorial reprsentation will make complex operations more intuitive many underlying properties may be able to be excavated. . Project should take approximately 3 months to reasonably complete. The projects will 1) build technical skills, increase our number of core contributors, and work on meaningful projects we want to integrate into Qiskit or maintain; 2) Tackle problems that relate to advancing quantum computing. This should transform into patents and papers.

# Mentor/s
<Are you able to mentor this project?> no

# Type of participant
<What are the profiles of the ideal participants for this idea?> Some with good quantum physics/computation, some with strong linear algebra, some with tensor networks and some with strong python skills

# Number of participants
4/5

# Deliverable
Patent and Paper

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
