### ISSUE TITLE
Grover's algorithm with Oracle implemented through Random Walk

### ISSUE THREAD

**Issue by amitracal** [qiskit-advocate/qamp-fall-21#41]
# Description
Grover's algorithm with Oracle implemented through Random Walk is a very interesting setup which was used in the final problem of IBM Quantum Challenge Fall 2020. But this concept can be enhanced. This project should take approximately 3 months to reasonably complete. The projects will 1) build technical skills, increase our number of core contributors, and work on meaningful projects we want to integrate into Qiskit or maintain; 2) Tackle problems that relate to advancing quantum computing. We should be able to publish paper and make patents on this.

# Mentor/s
<Are you able to mentor this project?>no

# Type of participant
With strong background on optimization (classical and quantum), python programming, qiskit

# Number of participants
4/5

# Deliverable
Patent and paper

**Comment by Feigenbaum4669** [comment]
Hi, I am also interested. I was implementing random walks on graphs in Qiskit a couple of years ago.
[(https://github.com/Feigenbaum4669/WPPT-quantum_walks](url)
[https://www.youtube.com/watch?v=gtcnxhpeNEQ](url)

**Comment by HuangJunye** [comment]
Close due to no mentor. Of course you are feel to organize yourselves outside the mentorship program if you are still interested.
